/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopRouteImport } from './routes/_shop'
import { Route as ShopBarangRouteImport } from './routes/_shop/barang'
import { Route as ShopBonRouteImport } from './routes/_shop/bon'
import { Route as ShopDashboardRouteImport } from './routes/_shop/dashboard'
import { Route as ShopJejakRouteImport } from './routes/_shop/jejak'
import { Route as ShopKasRouteImport } from './routes/_shop/kas'
import { Route as ShopKasirRouteImport } from './routes/_shop/kasir'
import { Route as ShopLaporanKasRouteImport } from './routes/_shop/laporan-kas'
import { Route as ShopManualRouteImport } from './routes/_shop/manual'
import { Route as ShopMitraRouteImport } from './routes/_shop/mitra'
import { Route as ShopPajakRouteImport } from './routes/_shop/pajak'
import { Route as ShopPengaturanRouteImport } from './routes/_shop/pengaturan'
import { Route as ShopReturRouteImport } from './routes/_shop/retur'
import { Route as ShopRiwayatRouteImport } from './routes/_shop/riwayat'
import { Route as ShopStokRouteImport } from './routes/_shop/stok'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopBarangRoute = ShopBarangRouteImport.update({
  id: '/barang',
  path: '/barang',
  getParentRoute: () => ShopRoute,
} as any)
const ShopBonRoute = ShopBonRouteImport.update({
  id: '/bon',
  path: '/bon',
  getParentRoute: () => ShopRoute,
} as any)
const ShopDashboardRoute = ShopDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShopRoute,
} as any)
const ShopJejakRoute = ShopJejakRouteImport.update({
  id: '/jejak',
  path: '/jejak',
  getParentRoute: () => ShopRoute,
} as any)
const ShopKasRoute = ShopKasRouteImport.update({
  id: '/kas',
  path: '/kas',
  getParentRoute: () => ShopRoute,
} as any)
const ShopKasirRoute = ShopKasirRouteImport.update({
  id: '/kasir',
  path: '/kasir',
  getParentRoute: () => ShopRoute,
} as any)
const ShopLaporanKasRoute = ShopLaporanKasRouteImport.update({
  id: '/laporan-kas',
  path: '/laporan-kas',
  getParentRoute: () => ShopRoute,
} as any)
const ShopManualRoute = ShopManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => ShopRoute,
} as any)
const ShopMitraRoute = ShopMitraRouteImport.update({
  id: '/mitra',
  path: '/mitra',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPajakRoute = ShopPajakRouteImport.update({
  id: '/pajak',
  path: '/pajak',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPengaturanRoute = ShopPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => ShopRoute,
} as any)
const ShopReturRoute = ShopReturRouteImport.update({
  id: '/retur',
  path: '/retur',
  getParentRoute: () => ShopRoute,
} as any)
const ShopRiwayatRoute = ShopRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => ShopRoute,
} as any)
const ShopStokRoute = ShopStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/barang': typeof ShopBarangRoute
  '/bon': typeof ShopBonRoute
  '/dashboard': typeof ShopDashboardRoute
  '/jejak': typeof ShopJejakRoute
  '/kas': typeof ShopKasRoute
  '/kasir': typeof ShopKasirRoute
  '/laporan-kas': typeof ShopLaporanKasRoute
  '/manual': typeof ShopManualRoute
  '/mitra': typeof ShopMitraRoute
  '/pajak': typeof ShopPajakRoute
  '/pengaturan': typeof ShopPengaturanRoute
  '/retur': typeof ShopReturRoute
  '/riwayat': typeof ShopRiwayatRoute
  '/stok': typeof ShopStokRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/barang': typeof ShopBarangRoute
  '/bon': typeof ShopBonRoute
  '/dashboard': typeof ShopDashboardRoute
  '/jejak': typeof ShopJejakRoute
  '/kas': typeof ShopKasRoute
  '/kasir': typeof ShopKasirRoute
  '/laporan-kas': typeof ShopLaporanKasRoute
  '/manual': typeof ShopManualRoute
  '/mitra': typeof ShopMitraRoute
  '/pajak': typeof ShopPajakRoute
  '/pengaturan': typeof ShopPengaturanRoute
  '/retur': typeof ShopReturRoute
  '/riwayat': typeof ShopRiwayatRoute
  '/stok': typeof ShopStokRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shop': typeof ShopRouteWithChildren
  '/_shop/barang': typeof ShopBarangRoute
  '/_shop/bon': typeof ShopBonRoute
  '/_shop/dashboard': typeof ShopDashboardRoute
  '/_shop/jejak': typeof ShopJejakRoute
  '/_shop/kas': typeof ShopKasRoute
  '/_shop/kasir': typeof ShopKasirRoute
  '/_shop/laporan-kas': typeof ShopLaporanKasRoute
  '/_shop/manual': typeof ShopManualRoute
  '/_shop/mitra': typeof ShopMitraRoute
  '/_shop/pajak': typeof ShopPajakRoute
  '/_shop/pengaturan': typeof ShopPengaturanRoute
  '/_shop/retur': typeof ShopReturRoute
  '/_shop/riwayat': typeof ShopRiwayatRoute
  '/_shop/stok': typeof ShopStokRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/barang'
    | '/bon'
    | '/dashboard'
    | '/jejak'
    | '/kas'
    | '/kasir'
    | '/laporan-kas'
    | '/manual'
    | '/mitra'
    | '/pajak'
    | '/pengaturan'
    | '/retur'
    | '/riwayat'
    | '/stok'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/barang'
    | '/bon'
    | '/dashboard'
    | '/jejak'
    | '/kas'
    | '/kasir'
    | '/laporan-kas'
    | '/manual'
    | '/mitra'
    | '/pajak'
    | '/pengaturan'
    | '/retur'
    | '/riwayat'
    | '/stok'
  id:
    | '__root__'
    | '/'
    | '/_shop'
    | '/_shop/barang'
    | '/_shop/bon'
    | '/_shop/dashboard'
    | '/_shop/jejak'
    | '/_shop/kas'
    | '/_shop/kasir'
    | '/_shop/laporan-kas'
    | '/_shop/manual'
    | '/_shop/mitra'
    | '/_shop/pajak'
    | '/_shop/pengaturan'
    | '/_shop/retur'
    | '/_shop/riwayat'
    | '/_shop/stok'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopRoute: typeof ShopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/barang': {
      id: '/_shop/barang'
      path: '/barang'
      fullPath: '/barang'
      preLoaderRoute: typeof ShopBarangRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/bon': {
      id: '/_shop/bon'
      path: '/bon'
      fullPath: '/bon'
      preLoaderRoute: typeof ShopBonRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/dashboard': {
      id: '/_shop/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShopDashboardRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/jejak': {
      id: '/_shop/jejak'
      path: '/jejak'
      fullPath: '/jejak'
      preLoaderRoute: typeof ShopJejakRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/kas': {
      id: '/_shop/kas'
      path: '/kas'
      fullPath: '/kas'
      preLoaderRoute: typeof ShopKasRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/kasir': {
      id: '/_shop/kasir'
      path: '/kasir'
      fullPath: '/kasir'
      preLoaderRoute: typeof ShopKasirRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/laporan-kas': {
      id: '/_shop/laporan-kas'
      path: '/laporan-kas'
      fullPath: '/laporan-kas'
      preLoaderRoute: typeof ShopLaporanKasRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/manual': {
      id: '/_shop/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ShopManualRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/mitra': {
      id: '/_shop/mitra'
      path: '/mitra'
      fullPath: '/mitra'
      preLoaderRoute: typeof ShopMitraRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/pajak': {
      id: '/_shop/pajak'
      path: '/pajak'
      fullPath: '/pajak'
      preLoaderRoute: typeof ShopPajakRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/pengaturan': {
      id: '/_shop/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof ShopPengaturanRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/retur': {
      id: '/_shop/retur'
      path: '/retur'
      fullPath: '/retur'
      preLoaderRoute: typeof ShopReturRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/riwayat': {
      id: '/_shop/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof ShopRiwayatRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/stok': {
      id: '/_shop/stok'
      path: '/stok'
      fullPath: '/stok'
      preLoaderRoute: typeof ShopStokRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopBarangRoute: typeof ShopBarangRoute
  ShopBonRoute: typeof ShopBonRoute
  ShopDashboardRoute: typeof ShopDashboardRoute
  ShopJejakRoute: typeof ShopJejakRoute
  ShopKasRoute: typeof ShopKasRoute
  ShopKasirRoute: typeof ShopKasirRoute
  ShopLaporanKasRoute: typeof ShopLaporanKasRoute
  ShopManualRoute: typeof ShopManualRoute
  ShopMitraRoute: typeof ShopMitraRoute
  ShopPajakRoute: typeof ShopPajakRoute
  ShopPengaturanRoute: typeof ShopPengaturanRoute
  ShopReturRoute: typeof ShopReturRoute
  ShopRiwayatRoute: typeof ShopRiwayatRoute
  ShopStokRoute: typeof ShopStokRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopBarangRoute: ShopBarangRoute,
  ShopBonRoute: ShopBonRoute,
  ShopDashboardRoute: ShopDashboardRoute,
  ShopJejakRoute: ShopJejakRoute,
  ShopKasRoute: ShopKasRoute,
  ShopKasirRoute: ShopKasirRoute,
  ShopLaporanKasRoute: ShopLaporanKasRoute,
  ShopManualRoute: ShopManualRoute,
  ShopMitraRoute: ShopMitraRoute,
  ShopPajakRoute: ShopPajakRoute,
  ShopPengaturanRoute: ShopPengaturanRoute,
  ShopReturRoute: ShopReturRoute,
  ShopRiwayatRoute: ShopRiwayatRoute,
  ShopStokRoute: ShopStokRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopRoute: ShopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
